### PR TITLE
Events and gmrecap eric chen

### PR DESCRIPTION
**Pull request by ericchenericchen**
Not the prettiest rn, I will be adding assets and reformatting how our main works tonight so it will be a lot more fleshed out.
- reformatting bootstrap design for mobile view
- making the general structure for event and gm recap
- rebasing from current homepage design

### CODE REVIEW

**Comment by ericchenericchen** [comment]
Need to fix 10/12:
- add assets
- remove inline styling
- margins and padding
- add icons for styling/other CSS for title/format

**Review by zhangeth — CHANGES_REQUESTED** [review]
Is all this necessary? Event description should already be apart of the picture. From what I imagined all we really need is a row with some columns containing the pictures. See the new yorker reference.

**Review by zhangeth — CHANGES_REQUESTED** [review]
Make into separate rows. Use the img styling so it does the transitions on hover.

**Comment by ericchenericchen** [comment]
> Make into separate rows. Use the img styling so it does the transitions on hover.

Fixed this, also fixed mobile interfacing if you can take a look sometime.

**Comment by zhangeth** [comment]
Done in different branch.

**Pull request closed without merging**
